name: Test SITRAP scraper

on:
  workflow_dispatch: {}

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Show Chrome version
        run: chrome --version

      - name: Run scraper (headless)
        env:
          DOWNLOAD_DIR: ${{ github.workspace }}/downloads
        run: |
          mkdir -p "$DOWNLOAD_DIR"
          python pescadiaria_app.py
          echo "Archivos descargados:"
          ls -lah "$DOWNLOAD_DIR" || true

      - name: Upload downloads as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sitrap-descargas
          path: downloads/
          if-no-files-found: warn
          retention-days: 7

